
services:
  template-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: template-service
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    command: ["sh", "-lc", "python -m uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${PORT:-8000}/docs || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3
