name: '🧪 CI - Lint GH Workflows'

on:
  push:
    paths:
      - ".github/workflows/**"

  pull_request:
    paths:
      - ".github/workflows/**"

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      checks: write              # needed for reporter=github-check
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1.41.0
        with:
          reporter: github-check         # or github-pr-review
          fail_on_error: true            # gate merges on failures
          actionlint_flags: "--color"    # optional: nicer local logs