name: "🧪 CI - Push (Unit)"

on:
  push:
    paths:
      - "app/**"
      - "tests/**"
      - "requirements-test.txt"
      - "requirements.txt"
      - "pytest.ini"
      - ".flake8"
      - ".pre-commit-config.yaml"
  workflow_call:

jobs:
  unit_api:
    name: Unit/Contract | ${{ matrix.os }} | Py ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022]
        python: ["3.10.8"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Cache pip downloads
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ matrix.python }}-${{ hashFiles('requirements.txt', 'requirements-test.txt', '**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python }}-
            ${{ runner.os }}-pip-

      - name: Log pip cache result
        run: |
          echo "Cache hit for pip downloads: ${{ steps.cache-pip.outputs.cache-hit }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-test.txt

      - name: Fetch Camoufox resources
        env:
          CAMOUFOX_MAX_RETRIES: 3
          CAMOUFOX_RETRY_DELAY: 10
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            pwsh -ExecutionPolicy Bypass -File ./.github/workflows/scripts/ci/fetch_camoufox.ps1
          else
            chmod +x ./.github/workflows/scripts/ci/fetch_camoufox.sh
            ./.github/workflows/scripts/ci/fetch_camoufox.sh
          fi
        shell: bash

      - name: Lint
        run: flake8 app/ tests/

      - name: Run tests (skip integration)
        run: python -m pytest -q -m "not integration" --disable-warnings --maxfail=1
