name: CI

on:
  push:          # any branch
  pull_request:

jobs:
  unit_api:
    name: Unit/Contract • ${{ matrix.os }} • Py ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        python: ["3.10", "3.11", "3.12", "3.13"]   # adjust if you standardize on another version
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PIP_CACHE_DIR: ~/.cache/pip
      PYTHONUNBUFFERED: "1"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ${{ runner.os }}-${{ matrix.os }}-pip-${{ matrix.python }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-${{ matrix.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Lint
        run: flake8 app/

      - name: Run tests (skip integration)
        run: python -m pytest -q -m "not integration" --disable-warnings --maxfail=1
